name: "upload binary"
description: "upload binary wrapper"

inputs:
  os:
    description: "os"
    required: true
  arch:
    description: "architecture"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/upload-artifact@v2
      with:
        name: ${{inputs.os}}-${{inputs.arch}}-libbls384_256.a
        path: bls/lib/${{inputs.os}}/${{inputs.arch}}/libbls384_256.a
