name: Release
on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  archive-binaries:
    name: archive binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
    if: contains(github.head_ref, 'release_os')
    steps:
      - uses: actions/checkout@v2
      - run: go test -v ./bls
      - run: git submodule update --init --recursive
      - name: build on linux with x86_64
        if: runner.os == 'Linux'
        run: |
          sudo apt install nasm
          make clean
          make CXX=clang++
          go test -v ./bls
      - name: build on linux with arm64
        if: runner.os == 'Linux'
        run: |
          sudo apt install -y make clang libstdc++-8-dev-arm64-cross
          make clean
          make CXX=clang++ COMPILE_TARGET=linux-arm64
      - if: runner.os == 'Linux'
        uses: ./.github/actions/upload-binary-action
        with:
          os: linux
          arch: amd64
      - if: runner.os == 'Linux'
        uses: ./.github/actions/upload-binary-action
        with:
          os: linux
          arch: arm64

      - name: build on mac with x86_64
        if: runner.os == 'macOS'
        run: |
          brew install nasm
          make clean
          make
          go test -v ./bls
      - name: build on mac with arm64
        if: runner.os == 'macOS'
        run: |
          make clean
          make CXX=clang++ COMPILE_TARGET=mac-m1
      - if: runner.os == 'macOS'
        uses: ./.github/actions/upload-binary-action
        with:
          os: darwin
          arch: amd64
      - if: runner.os == 'macOS'
        uses: ./.github/actions/upload-binary-action
        with:
          os: darwin
          arch: arm64

  commit-binaries:
    name: commit binaries
    runs-on: ubuntu-latest
    needs: archive-binaries
    env:
      BRANCH_NAME: ${{github.head_ref}}  # The branch name to merge
    steps:
      - if: ${{ github.event.action }} == push
        run: |
          echo "BRANCH_NAME=master" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: ./.github/actions/upload-binary-action
        with:
          os: linux
          arch: amd64
      - uses: ./.github/actions/upload-binary-action
        with:
          os: linux
          arch: arm64
      - uses: ./.github/actions/upload-binary-action
        with:
          os: darwin
          arch: amd64
      - uses: ./.github/actions/upload-binary-action
        with:
          os: darwin
          arch: arm64

      - name: commit binaries
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add bls/lib/*
          git commit -m "[skip ci] add binaries(linux/amd64, linux/arm64, darwin/amd64, darwin/arm64)"
          git push origin HEAD
